name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish
    - name: Upload WebApiDemo Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApiDemo
        path: /home/runner/work/WebApiDemo/WebApiDemo/WebApiDemo/bin/Debug/netcoreapp3.1/publish/
